---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2023/8/30 16:59
---

-- KEYS[1]: PROMOTION_promotionId_STOCK

-- 1. check promotion stock (key) existing
if redis.call('exists', KEYS[1]) == 1
then
    -- 2. get value by key
    local stock = tonumber(redis.call('get', KEYS[1]));
    -- 3. stock > 0 then lock stock
    if (stock > 0)

        then
        redis.call('set', KEYS[1], stock-1);
        return stock-1;
    end
    -- 4. sold out
    return -1;
end
-- 5. key not exist
return -2;