server:
  port: 8090



spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: # 是否注册（默认为true）
        register: true
        # 服务名称
        service-name: ${spring.application.name}
        # 展示实例的ip（默认是false）
        prefer-ip-address: true
        # 实例id名称（默认是${spring.application.name}:comma,separated,profiles:${server.port}）
        # instance-id: ${spring.application.name}

    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态路由，使用注册中心的微服务进行路由
          lower-case-service-id: true
      globalcors:
        # 支持浏览器CORS preflight options请求
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          # !!! 仅在开发环境设置为 "*"
          '[/**]':
            allowedOrigins: "http://localhost:8804"
            allowedHeaders: "*"
            allowedMethods: "*"
            exposedHeaders: "*"
            allowCredentials: true
            maxAge: 86400
      routes:
        - id: account-route
          # uri: http://localhsot:8008
          # url: lb:// consul里面的server_name
          # uri: http://localhsot:8070
          uri: lb://user-service
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=0
        - id: commodity-route
          # uri: http://localhsot:8008
          # url: lb:// consul里面的server_name
          # uri: http://localhsot:8070
          uri: lb://commodity-service
          predicates:
            - Path=/commodity/**
          filters:
            - StripPrefix=0
        - id: system-route
          # uri: http://localhsot:8008
          # url: lb:// consul里面的server_name
          # uri: http://localhsot:8070
          uri: lb://user-service
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=0
        - id: promotion-route
          # uri: http://localhsot:8008
          # url: lb:// consul里面的server_name
          # uri: http://localhsot:8070
          uri: lb://promotion-service
          predicates:
            - Path=/promotion/**
          filters:
            - StripPrefix=0
        - id: order-route-1
          # uri: http://localhsot:8008
          # url: lb:// consul里面的server_name
          # uri: http://localhsot:8070
          uri: lb://order-service-1
          predicates:
            - Path=/order/**
          #  - Header=mark, 1
          filters:
            - StripPrefix=0