/*
 * This file is generated by jOOQ.
 */
package com.skillup.infrastructure.jooq;


import com.skillup.infrastructure.jooq.tables.Orders;
import com.skillup.infrastructure.jooq.tables.Promotion;
import com.skillup.infrastructure.jooq.tables.User;


/**
 * Convenience access to all tables in skillup.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>skillup.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>skillup.promotion</code>.
     */
    public static final Promotion PROMOTION = Promotion.PROMOTION;

    /**
     * The table <code>skillup.user</code>.
     */
    public static final User USER = User.USER;
}
