/*
 * This file is generated by jOOQ.
 */
package com.skillup.infrastructure.jooq;


import com.skillup.infrastructure.jooq.tables.Promotion;
import com.skillup.infrastructure.jooq.tables.PromotionLog;


/**
 * Convenience access to all tables in promotion-service.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>promotion-service.promotion</code>.
     */
    public static final Promotion PROMOTION = Promotion.PROMOTION;

    /**
     * The table <code>promotion-service.promotion_log</code>.
     */
    public static final PromotionLog PROMOTION_LOG = PromotionLog.PROMOTION_LOG;
}
