/*
 * This file is generated by jOOQ.
 */
package com.skillup.infrastructure.jooq;


import com.skillup.infrastructure.jooq.tables.User;


/**
 * Convenience access to all tables in user-service.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user-service.user</code>.
     */
    public static final User USER = User.USER;
}
